### ISSUE TITLE
Integrate automated installation of RoonBridge

### ISSUE THREAD

**Issue by ratcashdev** [moode-player/mosbuild#8]
Following http://moodeaudio.org/forum/showthread.php?tid=3200 is easy for the technically skilled to install RoonBridge.
However, out-of-the-box experience would be better for Roon users if one did not need to use SSH.

Would it be possible to automate the installation of RoonBridge? Not baking it into the resulting image, but including some scripts to download/install when the OS installation is done (similarly to how Roopie did into Moode OS).

Where would we need to do the necessary changes?

**Comment by moodeaudio** [comment]
Better to ask Roon to license it as Open Source then anyone could simply fork and bundle it.

As far as integrated install scripts go, I'm not really interested in developing and maintaining such a thing because it becomes yet another support vector for our project when it doesn't work. it's always possible though that another dev will do the coding, submit a PR and commit to supporting it.

**Comment by ratcashdev** [comment]
I understand your position. I'd appreciate if you could perhaps provide some hints and guidance as it would make the preparation of the PR much easier.
